from youtube_comment_downloader import YoutubeCommentDownloader, SORT_BY_POPULAR
import json
import os

# List of YouTube video URLs
video_urls = [
    "https://www.youtube.com/watch?v=pI0ZjZjDG-o",
    "https://www.youtube.com/watch?v=GGxVeMemDxA",
    "https://www.youtube.com/watch?v=fThZlFAxEDI",
    "https://www.youtube.com/watch?v=R6PzFtPF5YQ",
    "https://www.youtube.com/watch?v=Bwii653RlGo",
    "https://www.youtube.com/watch?v=9z0ZqKsYOtA",
    "https://www.youtube.com/watch?v=c3NEeYDMsrI",
    "https://www.youtube.com/watch?v=ZF6DzZmcSOk",
    "https://www.youtube.com/watch?v=nRPnOsg2lNo",
    "https://www.youtube.com/watch?v=WN8qvFXmRhM",
    "https://www.youtube.com/watch?v=_D2umY5ziYs",
    "https://www.youtube.com/watch?v=cWnL2mwda_I",
    "https://www.youtube.com/watch?v=YWFkSza-7dY",
    "https://www.youtube.com/watch?v=8w7wwxLbAGU",
    "https://www.youtube.com/watch?v=52WZSOn1ybs",
    "https://www.youtube.com/watch?v=aSwULzpnB3Y",
    "https://www.youtube.com/watch?v=euTbRNugg14",
    "https://www.youtube.com/watch?v=Mmrc0zX31e4",
    "https://www.youtube.com/watch?v=9OZaLtGH-Z0",
    "https://www.youtube.com/watch?v=1ad3RqKH_dE",
    "https://www.youtube.com/watch?v=lj5b9MKHaSo",
    "https://www.youtube.com/watch?v=nJfQmwgIUY8",
    "https://www.youtube.com/watch?v=Wv4l20pUz1Y",
    "https://www.youtube.com/watch?v=YNwkZZw-tgA",
    "https://www.youtube.com/watch?v=FdNZ7j5A7M8",
    "https://www.youtube.com/watch?v=7tXN711S1rc",
    "https://www.youtube.com/watch?v=UDxCddm9Cn8",
    "https://www.youtube.com/watch?v=RicvZHSezKo",
    "https://www.youtube.com/watch?v=_iZ_0W6t9tY",
    "https://www.youtube.com/watch?v=IcijBrFUY9M",
    "https://www.youtube.com/watch?v=SUjmfEIW0UQ",
    "https://www.youtube.com/watch?v=GAxSDAdPHn4",
    "https://www.youtube.com/watch?v=xEccjz6_kTI",
    "https://www.youtube.com/watch?v=xky3esrwWCc",
    "https://www.youtube.com/watch?v=COfWkLnUHH8",
    "https://www.youtube.com/watch?v=ViKDudWdBmQ",
    "https://www.youtube.com/watch?v=SavtkxaBzVI",
    "https://www.youtube.com/watch?v=EtxQZwq0xvg",
    "https://www.youtube.com/watch?v=IDh_RmgysM0",
    "https://www.youtube.com/watch?v=3k-ZmP_pM6U",
    "https://www.youtube.com/watch?v=rCs0bAPo9eQ",
    "https://www.youtube.com/watch?v=UWY9imA5m7A",
    "https://www.youtube.com/watch?v=xAAJFyoG0q0",
    "https://www.youtube.com/watch?v=Uyl7iwmgOTc",
    "https://www.youtube.com/watch?v=-u4hi75H8BE",
    "https://www.youtube.com/watch?v=sBzNeW_Up6w",
    "https://www.youtube.com/watch?v=Rtl9cU5qses",
    "https://www.youtube.com/watch?v=wDWKYWbHo20",
    "https://www.youtube.com/watch?v=zX9abLVFiPY",
    "https://www.youtube.com/watch?v=Xasd5az5bzM",
    "https://www.youtube.com/watch?v=nwZqnpclDvg",
    "https://www.youtube.com/watch?v=_YddTPxw_68",
    "https://www.youtube.com/watch?v=0hy2chz8tJ4",
    "https://www.youtube.com/watch?v=BEGuLAtvufg",
    "https://www.youtube.com/watch?v=PoCjSmQwnHk",
    "https://www.youtube.com/watch?v=ZeNqR6liTco",
    "https://www.youtube.com/watch?v=XE9iMu2Kz58",
    "https://www.youtube.com/watch?v=ZUpw4GE4PM0",
    "https://www.youtube.com/watch?v=FUCIC_lUSLk",
    "https://www.youtube.com/watch?v=jlHDFQmvj1s",
    "https://www.youtube.com/watch?v=APXMYJCKzr8",
    "https://www.youtube.com/watch?v=A3_TKH_UY0A",
    "https://www.youtube.com/watch?v=GC8H7PLQIbw",
    "https://www.youtube.com/watch?v=fiLpHQhB1Ko",
    "https://www.youtube.com/watch?v=00HHQHAj_cQ",
    "https://www.youtube.com/watch?v=YMEpgNgOlFQ",
    "https://www.youtube.com/watch?v=Ukl5cwIklOY",
    "https://www.youtube.com/watch?v=1ALL8-nGrOM",
    "https://www.youtube.com/watch?v=knegxpTT2HA",
    "https://www.youtube.com/watch?v=ZXffuP09tX0",
    "https://www.youtube.com/watch?v=CjzXPFbTljk",
    "https://www.youtube.com/watch?v=-8OTlpM2WUs",
    "https://www.youtube.com/watch?v=hNllPA3sRyk",
    "https://www.youtube.com/watch?v=Bhk4FHq9zBs",
    "https://www.youtube.com/watch?v=vMwrkuhoHG4",
    "https://www.youtube.com/watch?v=4QuJbq_yo4M",
    "https://www.youtube.com/watch?v=H2E6XLY6wFE",
    "https://www.youtube.com/watch?v=kTZ-a9BGR-w",
    "https://www.youtube.com/watch?v=5fnzCW4zclo",
    "https://www.youtube.com/watch?v=NnH9XlazbkA",
    "https://www.youtube.com/watch?v=bc25H3mDZBo",
    "https://www.youtube.com/watch?v=zTT2Jx2WQzk",
    "https://www.youtube.com/watch?v=BnDW889QyYQ",
    "https://www.youtube.com/watch?v=3J2vbUUOTTs",
    "https://www.youtube.com/watch?v=FnWZ72Xtv78",
    "https://www.youtube.com/watch?v=JKXRak7a6e4",
    "https://www.youtube.com/watch?v=jkcCjye8sO8",
    "https://www.youtube.com/watch?v=dc5983-LrFk",
    "https://www.youtube.com/watch?v=2M4ETZlcmm4",
    "https://www.youtube.com/watch?v=nGjdrVpaiI4",
    "https://www.youtube.com/watch?v=Urmm3xlk6Dk",
    "https://www.youtube.com/watch?v=U66g4DXK3Ns",
    "https://www.youtube.com/watch?v=CCIgKcR0Hjo",
    "https://www.youtube.com/watch?v=h2yp0ncxxyA",
    "https://www.youtube.com/watch?v=p5FOY1GnL0I",
    "https://www.youtube.com/watch?v=DekLdzMWVn0",
    "https://www.youtube.com/watch?v=wwVCjMWIfQA",
    "https://www.youtube.com/watch?v=nrRke9zZ0fo",
    "https://www.youtube.com/watch?v=HvKrLb333Z8",
    "https://www.youtube.com/watch?v=RwcI3a_w2pY",
    "https://www.youtube.com/watch?v=zbeyImmnaaQ",
    "https://www.youtube.com/watch?v=7Nqt4vRQBFg",
    "https://www.youtube.com/watch?v=OTXTmJqhBGM",
    "https://www.youtube.com/watch?v=PsfVYQ8zd4M",
    "https://www.youtube.com/watch?v=xjlIC2ra4R0",
    "https://www.youtube.com/watch?v=kCB7H0N4aog",
    "https://www.youtube.com/watch?v=GYRHdZDUCCA",
    "https://www.youtube.com/watch?v=QhjEgUpEADA",
    "https://www.youtube.com/watch?v=GDL592mCAEE",
    "https://www.youtube.com/watch?v=GafgvTd0Gzs",
    "https://www.youtube.com/watch?v=nErqgkH4BYE",
    "https://www.youtube.com/watch?v=9sBiFeu9mu4",
    "https://www.youtube.com/watch?v=QdRmxck6gXk",
    "https://www.youtube.com/watch?v=ReUSSljekP0",
    "https://www.youtube.com/watch?v=mFF0318EYic",
    "https://www.youtube.com/watch?v=TjLYjNYym8c",
    "https://www.youtube.com/watch?v=Q0eol_vhhH4",
    "https://www.youtube.com/watch?v=Ig-uhIumfEQ",
    "https://www.youtube.com/watch?v=T9_NSm-QKJ0",
    "https://www.youtube.com/watch?v=0BdzfKYo7Z8",
    "https://www.youtube.com/watch?v=r7KtO1G0J0g",
    "https://www.youtube.com/watch?v=YybkSxcgvIQ",
    "https://www.youtube.com/watch?v=acslEFdNMZw",
    "https://www.youtube.com/watch?v=lUkOfeKk4zM",
    "https://www.youtube.com/watch?v=0PesYk0rtgc",
    "https://www.youtube.com/watch?v=o9u0AOhk_xg",
    "https://www.youtube.com/watch?v=xXLXwVBlti0",
    "https://www.youtube.com/watch?v=i9mR8TzyYMg",
    "https://www.youtube.com/watch?v=m39lslv_AeI",
    "https://www.youtube.com/watch?v=-YVqYuqf850",
    "https://www.youtube.com/watch?v=im-W7D69o9Q",
    "https://www.youtube.com/watch?v=J2jrm838Gng",
    "https://www.youtube.com/watch?v=Tu8FA2OArbw",
    "https://www.youtube.com/watch?v=SjW0bMSLjTg",
    "https://www.youtube.com/watch?v=8Y8e79uFMRo",
    "https://www.youtube.com/watch?v=kzXPkoD3Lwg",
    "https://www.youtube.com/watch?v=HpEqMHPz-Y8",
    "https://www.youtube.com/watch?v=IoJzpFWc1Rc",
    "https://www.youtube.com/watch?v=dnW0Tzs0jgw",
    "https://www.youtube.com/watch?v=g8n9j274sTc",
    "https://www.youtube.com/watch?v=V4EnQORr-Rk",
    "https://www.youtube.com/watch?v=LIsSypoQvHQ",
    "https://www.youtube.com/watch?v=xV56v8uwo70",
    "https://www.youtube.com/watch?v=EyZI_GgrR-M",
    "https://www.youtube.com/watch?v=KQlb63QdX5E",
    "https://www.youtube.com/watch?v=fiSuVePMUzk",
    "https://www.youtube.com/watch?v=EbZ26Lp8d8w",
    "https://www.youtube.com/watch?v=ekJYIEw7n48",
    "https://www.youtube.com/watch?v=_59JAALzT0w",
    "https://www.youtube.com/watch?v=vVFuU_Hi0wk"
]


# Output folder
output_folder = "comments_data"
os.makedirs(output_folder, exist_ok=True)

downloader = YoutubeCommentDownloader()

for url in video_urls:
    video_id = url.split("v=")[1]
    print(f"Collecting comments from video ID: {video_id}")

    comments = []
    try:
        # Download comments sorted by popularity
        for comment in downloader.get_comments_from_url(url, sort_by=SORT_BY_POPULAR):
            comments.append(comment)
    except Exception as e:
        print(f"Error collecting comments from {url}: {e}")
        continue

    # Save comments to a JSON file
    output_path = os.path.join(output_folder, f"{video_id}_comments.json")
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(comments, f, ensure_ascii=False, indent=4)

    print(f"Saved {len(comments)} comments to {output_path}\n")
